export enum FacialLivenessDiagnostic {
  None = 0,
  Spoof = 1,
  Uncertain = 2,
  Live = 3,
  NoneBecauseBadQuality = 4,
  NoneBecauseFaceTooClose = 5,
  NoneBecauseFaceNotFound = 6,
  NoneBecauseFaceTooSmall = 7,
  NoneBecauseAngleTooLarge = 8,
  NoneBecauseImageDataError = 9,
  NoneBecauseInternalError = 10,
  NoneBecauseImagePreprocessError = 11,
  NoneBecauseTooManyFaces = 12,
  NoneBecauseFaceTooCloseToBorder = 13,
  NoneBecauseFaceCropped = 14,
  NoneBecauseLicenseError = 15,
}

export enum MapToFacialLivenessResult {
  None = "NONE",
  Spoof = "SPOOF",
  Uncertain = "UNCERTAIN",
  Live = "LIVE",
  NoneBecauseBadQuality = "NONE_BECAUSE_BAD_QUALITY",
  NoneBecauseFaceTooClose = "NONE_BECAUSE_FACE_TO_CLOSE",
  NoneBecauseFaceNotFound = "NONE_BECAUSE_FACE_NOT_FOUND",
  NoneBecauseFaceTooSmall = "NONE_BECAUSE_FACE_TOO_SMALL",
  NoneBecauseAngleTooLarge = "NONE_BECAUSE_ANGLE_TOO_LARGE",
  NoneBecauseImageDataError = "NONE_BECAUSE_IMAGE_DATA_ERROR",
  NoneBecauseInternalError = "NONE_BECAUSE_INTERNAL_ERROR",
  NoneBecauseImagePreprocessError = "NONE_BECAUSE_IMAGE_PREPROCESS_ERROR",
  NoneBecauseTooManyFaces = "NONE_BECAUSE_TOO_MANY_FACES",
  NoneBecauseFaceTooCloseToBorder = "NONE_BECAUSE_FACE_TOO_CLOSE_TO_BORDER",
  NoneBecauseFaceCropped = "NONE_BECAUSE_FACE_CROPPED",
  NoneBecauseLicenseError = "NONE_BECAUSE_LICENSE_ERROR",
}
