name: pruebas
on:
  #push:
  #  branches:
  #    - main
  #pull_request:
  #  branches: [main]     
  workflow_dispatch:


env:
  AWS_PROFILE: aen
  DOCKER_IMAGE: pruebas
  DOCKER_TAG: 1.0.0-SNAPSHOT
  
  
jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
     ## packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set Path
      run: |
        ls -l


    - name: Generate docker image
      run: | 
        docker build . -t ${{ env.DOCKER_IMAGE }}
  
    - name: Ver docker image
      run: | 
        docker images 
        
        
