name: pruebas
on:
  #push:
  #  branches:
  #    - main
  #pull_request:
  #  branches: [main]     
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
     ## packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set Path
      run: |
        ls -l


    - name: Generate docker image
      run: | 
        docker build . -t ${{ env.DOCKER_IMAGE }}
  
     - name: Ver docker image
      run: | 
        docker images 
        
        
        
    - name: install-awscli
      run: | 
        apt-get update && apt-get -y install awscli
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_ACCESS_KEY_SECRETS }} 
        aws configure set default.region ${{ secrets.AWS_REGION }}
        
    - name: Configure AWS credentials Develop
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_ACCESS_KEY_SECRETS }}
        aws-region: ${{ secrets.AWS_REGION }}
    
    
    
    - id: upload
      name: upload
      run: |
        aws ecr get-login-password \
          --region ${{ secrets.AWS_REGION }} \
          --profile ${{ env.AWS_PROFILE }} | \
          docker login \
          --username AWS \
          --password-stdin ${{ secrets.AWS_ECR_AEN }}
        docker tag ${{ env.DOCKER_IMAGE }} ${{ secrets.AWS_ECR_AEN }}/${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
        docker push ${{ secrets.AWS_ECR_AEN }}/${{ env.DOCKER_IMAGE }}:${{ env.DOCKER_TAG }}
        



