name: pruebas
on:
  push:
    branches:
      - main
  #pull_request:
  #  branches: [main]     
  workflow_dispatch:

env:
  AWS_PROFILE: mdelrosal

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
     ## packages: write

    steps:
    - uses: actions/checkout@v3

    - name: Set Path
      run: |
        ls -l
